#!/bin/bash
#
# When using this script, please describe in detail in the commit message
# for the resultant binaries which environment was used (e.g. stage3 tarball
# name, ::gentoo commit/date+time, stable or not, ...)
#
# See `print_build_commands` for building the binpkgs themselves, and
# `print_upload_commands` for retrieving them and uploading to dev.gentoo.org.
print_build_commands() {
	# For easy copy-pasting
	printf "# Printing build commands:\n"
	cat <<-EOF
	systemd-nspawn -D /srv/chroots/stage3-amd64-hardened-systemd-20241214T201851Z \\
		--bind=/srv/chroots/binpkgs/amd64-ada-bootstrap:/var/cache/binpkgs \\
		--bind-ro=/var/db/repos/gentoo \\
		--bind=/var/cache/distfiles \\
		--capability CAP_SYS_ADMIN \\
		--suppress-sync=true \\
		-M amd64-ada-bootstrap \\
		--background=
	emerge -vn eselect-repository crossdev
	eselect repository create crossdev
	echo 'FEATURES="\${FEATURES} buildpkg"' >> /etc/portage/make.conf
	echo 'BINPKG_FORMAT="gpkg"' >> /etc/portage/make.conf
	echo 'BINPKG_COMPRESS="xz"' >> /etc/portage/make.conf
	echo 'BINPKG_COMPRESS_FLAGS_XZ="-9e"' >> /etc/portage/make.conf
	bash ~/build-ada-bootstraps
	EOF
	printf "\n"
}

print_upload_commands() {
	# We don't want to set this for all functions because if unset, we'd rather
	# let crossdev pick the latest version as its logic is a bit brittle.
	# See https://bugs.gentoo.org/945296#c184.
	[[ -z ${GCC_VER} ]] && GCC_VER=$(gcc -dumpversion)

	# For easy copy-pasting
	printf "# Printing upload commands:\n"
	cat <<-EOF
	ADA_CHROOT=/srv/chroots/stage3-amd64-hardened-systemd-20241214T201851Z
	CATEGORY=dev-lang
	PN=ada-bootstrap

	readarray -d '' -t binpkgs < <(find \${ADA_CHROOT}/usr/*/var/cache/binpkgs/sys-devel/gcc/gcc-${GCC_VER%%.*}*.gpkg.tar -print0)
	for binpkg in "\${binpkgs[@]}" ; do
		target=\${binpkg#\${ADA_CHROOT}/usr/}
		target=\${target%/var/cache/binpkgs/*}
		#[[ \${target} != @(hppa*) && \${target} != hppa1* ]] && continue
		#[[ \${target} != @(loong*|m68k*|riscv64*|s390*|s390x*) ]] && continue
		sudo cp -v \${binpkg} /var/cache/distfiles/ada-bootstrap-${GCC_VER%%.*}-\${target}.gpkg.tar
		rsync --mkpath -av -P /var/cache/distfiles/ada-bootstrap-${GCC_VER%%.*}-\${target}.gpkg.tar dev.gentoo.org:~/public_html/distfiles/\${CATEGORY}/\${PN}/ada-bootstrap-${GCC_VER%%.*}-\${target}.gpkg.tar
	done
	EOF
}

build_crosses() {
	set -x

	TARGETS=(
		aarch64-unknown-linux-gnu
		alpha-unknown-linux-gnu
		arm-unknown-linux-gnu
		armv6j-softfp-linux-gnueabi
		armv6j-unknown-linux-gnueabihf
		armv7a-softfp-linux-gnueabi
		armv7a-unknown-linux-gnueabihf
		hppa1.1-unknown-linux-gnu
		hppa2.0-unknown-linux-gnu
		loongarch64-unknown-linux-gnu
		m68k-unknown-linux-gnu
		powerpc-unknown-linux-gnu
		powerpc64-unknown-linux-gnu
		powerpc64le-unknown-linux-gnu
		riscv32-unknown-linux-gnu
		riscv64-unknown-linux-gnu
		s390-ibm-linux-gnu
		s390x-ibm-linux-gnu
		sparc64-unknown-linux-gnu

		# TODO: x86, mips, other arm(?)
	)

	BASE_CROSSDEV_ARGS=(
		--ex-gcc
	)

	if [[ -n ${GCC_VER} ]] ; then
		BASE_CROSSDEV_ARGS+=(
			--gcc ${GCC_VER}
		)
	fi

	for CHOST in "${TARGETS[@]}" ; do
		yes | crossdev -C ${CHOST}

		arch=$(grep -m 1 -r ${CHOST} /var/db/repos/gentoo/profiles | cut -d/ -f8 | head -1)
		if grep -q "${arch}.*stable" /var/db/repos/gentoo/profiles/arches.desc ; then
			USE=ada crossdev ${CHOST} "${BASE_CROSSDEV_ARGS[@]}" -S || continue
			sed -i -e 's: ~${ARCH}::' "/usr/${CHOST}/etc/portage/make.conf"
		else
			USE=ada crossdev ${CHOST} "${BASE_CROSSDEV_ARGS[@]}" || continue
		fi

		sed -i -e 's:-O2:-Oz:' "/usr/${CHOST}/etc/portage/make.conf"
		echo 'BINPKG_FORMAT="gpkg"' >> "/usr/${CHOST}/etc/portage/make.conf"
		echo 'BINPKG_COMPRESS="xz"' >> "/usr/${CHOST}/etc/portage/make.conf"
		echo 'BINPKG_COMPRESS_FLAGS_XZ="-9e"' >> "/usr/${CHOST}/etc/portage/make.conf"

		mkdir "/usr/${CHOST}/etc/portage/package.use"
		echo '*/* lto' >> "/usr/${CHOST}/etc/portage/package.use/lto"
		echo "sys-devel/gcc lto custom-cflags" >> "/usr/${CHOST}/etc/portage/package.use/gcc"
		echo "sys-devel/gcc -fortran -openmp -sanitize -nls" >> "/usr/${CHOST}/etc/portage/package.use/gcc"

		mkdir "/usr/${CHOST}/etc/portage/profile/package.use.mask"
		echo "sys-devel/gcc -custom-cflags" >> "/usr/${CHOST}/etc/portage/profile/package.use.mask/gcc"

		USE=ada ${CHOST}-emerge -v1 sys-devel/gcc
	done
}

GCC_VER=12.5
print_build_commands
#print_upload_commands
#build_crosses