#!/usr/bin/env bash
# Usage: create keys.txt with newline-separated fingerprints
set -u

prefix="proj-keys-$(date -u +%Y%m%d)"
separate_key_files=0

KEYSERVERS=(
	hkps://keyserver.ubuntu.com
	hkps://pgp.mit.edu
	hkps://keys.gentoo.org
	hkps://keys.openpgp.org
	hkps://keyserver.pgp.com
	hkps://keys.gnupg.net
	hkps://pgpkeys.eu
)

tmp=$(mktemp -d)

while read fingerprint keyholder_name; do
	for keyserver in "${KEYSERVERS[@]}" ; do
		gpg --no-default-keyring --keyring "${tmp}"/keyring.asc --batch --keyserver ${keyserver} --recv-keys ${fingerprint}
	done

	if [[ ${separate_key_files} -eq 1 ]] ; then
		gpg --no-default-keyring --keyring "${tmp}"/keyring.asc --export "${fingerprint}" > "${tmp}"/${prefix}-${fingerprint}.asc
		echo "${tmp}"/${prefix}-${fingerprint}.asc
	fi

done < ./keys.txt

if [[ ${separate_key_files} -eq 0 ]] ; then
	gpg --no-default-keyring --keyring "${tmp}"/keyring.asc --export --armor > "${tmp}"/keys.asc
	echo "${tmp}"/keys.asc
fi
