#!/usr/bin/env bash
. /lib/gentoo/functions.sh
. /usr/share/iwdevtools/atomf.bashlib

ebuild=${1}
version=$(atomf "%V" "${ebuild/.ebuild}")
pf=$(atomf "%n%v%r" "${ebuild/.ebuild}")

QEMU_DOCS_PREBUILT=0 USE=doc ebuild ${1} manifest clean compile

dir=$(mktemp -d)
mkdir "${dir}"/qemu-${version}-docs

ebegin "Copying docs to ${dir}/qemu-7.0.0-docs"
cp -ra /var/tmp/portage/app-emulation/${pf}/work/qemu-*/tools-build/docs "${dir}"/qemu-${version}-docs/
eend $? || exit 1

# We don't want the HTML docs
rm -rf /var/tmp/portage/app-emulation/${pf}/work/qemu-*/tools-build/docs/manual

ebegin "Creating tarball"
tar -caf "${dir}"/qemu-${version}-docs.tar.xz -C "${dir}" qemu-${version}-docs/
eend $? || exit 1

einfo "Tarball at ${dir}/qemu-${version}-docs.tar.xz"
