#!/usr/bin/env bash
if [[ ${BASH_SOURCE} = */* ]]; then
	SCRIPT_DIR=${BASH_SOURCE%/*}/
else
	SCRIPT_DIR=./
fi

. ${SCRIPT_DIR}/generate-docs.bashlib || { echo "Failed to source generate-docs.bashlib!" ; exit 1 ; }

export IPUTILS_DOCS_PREBUILT=0
export EGIT_OVERRIDE_COMMIT_IPUTILS_IPUTILS="$2"
export USE="arping caps clockdiff doc idn nls test tracepath"

generate-docs_copy_docs() {
	ebegin "Copying docs to ${dir}/${P}-docs"
	cp -ra "${WORKDIR}"/${P}-build/doc "${dir}"/${P}-docs/
	eend $? || exit 1
}

generate-docs $@
