#!/usr/bin/env bash
if [[ ${BASH_SOURCE} = */* ]]; then
	SCRIPT_DIR=${BASH_SOURCE%/*}/
else
	SCRIPT_DIR=./
fi

. ${SCRIPT_DIR}/generate-docs.bashlib

atomset ${1}

export LIBUNWIND_DOCS_PREBUILT=0

generate-docs_copy_docs() {
	ebegin "Copying docs to ${dir}/${P}-docs"
	cp -r "${D}"/usr/share/man*/* "${dir}"/${P}-docs/
	eend ${?} || exit 1
}

generate-docs $@
