#!/usr/bin/env bash
set -u

KEYSERVERS=(
	hkps://keyserver.ubuntu.com
	hkps://pgp.mit.edu
	hkps://keys.gentoo.org
	hkps://keys.openpgp.org
	hkps://pgp.surfnet.nl
	hkps://keyserver.pgp.com
	hkps://keys.gnupg.net
	hkps://pgpkeys.eu
	hkps://pgp-servers.net
)

for keyserver in "${KEYSERVERS[@]}" ; do
	gpg --batch --keyserver ${keyserver} --refresh-keys
done
