#!/usr/bin/env bash
# https://wiki.gentoo.org/wiki/Bisecting_with_live_ebuilds
# GPL-3+
. /lib/gentoo/functions.sh || { echo "Failed to source functions.sh!" ; exit 1 ; }

# TODO:
# * Add "profiles" (all lang, just C/C++)
# * Optionally build a fast compiler first if $CC is built with lots of checking
# * Maybe more cleanly put all the examples into functions to call/comment out
# * Maintain commit ranges where we know e.g. --disable-fixincludes works/doesn't
# * elfshaker integration/at least seeding it opportunistically?

esyslog() {
	: No need.
}

die() {
	eerror "$@"
	exit 255 # Abort the bisect process
}

fatal() {
	einfo Running "$@"
	"$@" || die "$@"
}

skip() {
	einfo Running "$@"
	if ! "$@"; then
		ewarn Build failed, skipping: "$@"
		exit 125
	fi
}

: "${CBUILD:=$(portageq envvar CBUILD)}"
export CBUILD
: "${CHOST:=$(portageq envvar CHOST)}"
export CHOST
: "${CTARGET:=$(portageq envvar CTARGET)}"
export CTARGET

: "${TMPDIR:=/tmp}"

cleanup() {
	[[ ${CLEANUP} == 1 ]] || return

	(
		git -C "${gitdir}" reset --hard HEAD
		git -C "${gitdir}" clean -fdx
	)
}

trap cleanup EXIT

if [[ -z ${CHOST} ]] ; then
	die "No CHOST set!"
fi

#
# Configuration
#

prefix="${TMPDIR}/gcc"
builddir="${TMPDIR}/build"

# Sensible defaults for sam
if [[ ${LOGNAME} == sam ]] ; then
	gitdir=~${LOGNAME}/git/gcc
else
	: "${gitdir:=${HOME}/gcc}"

	#prefix="/media/guest-homedirs/sam/build/bisect"
	#gitdir="/media/guest-homedirs/sam/git/gcc"
fi

CLEANUP=0
build_from_portage=0

#
# End configuration
#

# These are only used for Portage builds
export ACCEPT_KEYWORDS="**"
export FEATURES="ccache -collision-protect -protect-owned -userfetch -usersync -userpriv -usersandbox"
export EVCS_OFFLINE=1
export EGIT_CLONE_TYPE="mirror"
export EGIT_OVERRIDE_REPO_GCC="file:///${gitdir}"
export EGIT_OVERRIDE_COMMIT_GCC="$(git rev-parse HEAD)"
#export EGIT_OVERRIDE_COMMIT_GCC="e4b5fec75aa8d0d01f6e042ec2888ef92eaa932a"

if [[ -z ${prefix} ]] ; then
	die "No prefix set!"
fi

if [[ -z ${builddir} ]] ; then
	die "No builddir set (or empty)!"
fi

if [[ -z ${gitdir} || ! -d ${gitdir} ]] ; then
	die "No gitdir set (or empty)!"
fi

if [[ -n ${CLEANUP} && ${CLEANUP} == 1 ]] ; then
	fatal rm -rf "${builddir}"
fi

fatal git -C "${gitdir}" clean -fdx
fatal git -C "${gitdir}" reset --hard HEAD
patch -d "${gitdir}" -f -p1 < /root/gcc-musl/11.4.0-50_all_calloc_libgccjit.patch || true

#patch -d "${gitdir}" -f -p1 < /tmp/0001-Add-param-max-devirt-targets.patch || true

#patch -d "${gitdir}" -f -p1 < /tmp/float-patches/0001-middle-end-c-i386-libgcc-std-bfloat16_t-and-__bf16-a.patch || true
#patch -d "${gitdir}" -f -p1 < /tmp/float-patches/0001-builtins-Add-various-__builtin_-f-16-32-64-128-32x-6.patch || true
#patch -d "${gitdir}" -f -p1 < /tmp/float-patches/0002-builtins-Add-__builtin_nextafterf16b-builtin.patch || true
#patch -d "${gitdir}" -f -p1 < /tmp/float-patches/0003-builtins-Add-various-complex-builtins-for-_Float-16-.patch || true

#patch -d "${gitdir}" -f -p1 < /root/gcc-musl/11.4.0-50_all_calloc_libgccjit.patch || true
#patch -d "${gitdir}" -f -p1 < /etc/portage/patches/sys-devel/gcc\:16/0008-ada-pic.patch || true
#patch -d "${gitdir}" -f -p1 < /etc/portage/patches/sys-devel/gcc\:16/ada-fpie-hack.patch || true

fatal mkdir -p "${builddir}"
fatal cd "${builddir}"

if [[ -n ${CLEANUP} && ${CLEANUP} == 1 ]] ; then
	# Aggressively clean up the existing build
	make -C "${builddir}" clean
	fatal rm -rf "build-${CHOST}/" "host-${CHOST}/" "${CHOST}/"
	if [[ -d .git ]] ; then
		git clean -fdx
	fi
	fatal rm -rf "${prefix}"
fi

fatal mkdir -p "${prefix}"

export CFLAGS="-O2 -fdiagnostics-color=always -fno-checking"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-O1 -Wl,--as-needed"

: "${STAGE1_CFLAGS:=${CFLAGS}}"
: "${STAGE1_LDFLAGS:=${LDFLAGS}}"
: "${BOOT_CFLAGS:=${CFLAGS}}"
: "${BOOT_LDFLAGS:=${LDFLAGS}}"
: "${LDFLAGS_FOR_TARGET:=${LDFLAGS}}"

export STAGE1_CFLAGS
export STAGE1_LDFLAGS
export BOOT_CFLAGS
export BOOT_LDFLAGS
export LDFLAGS_FOR_TARGET

gcc_make_args=(
	-j"$(nproc)" -l"$(nproc)"
	CFLAGS="${CFLAGS}"
	CXXFLAGS="${CXXFLAGS}"
	LDFLAGS="${LDFLAGS}"
	STAGE1_CFLAGS="${STAGE1_CFLAGS}"
	STAGE1_LDFLAGS="${STAGE1_LDFLAGS}"
	BOOT_CFLAGS="${BOOT_CFLAGS}"
	BOOT_LDFLAGS="${BOOT_LDFLAGS}"
	LDFLAGS_FOR_TARGET="${LDFLAGS_FOR_TARGET}"
)

gcc_config_args=(
	--build="${CBUILD:-${CHOST}}"
	--host="${CHOST}"
	--target="${CTARGET:-${CHOST}}"

	--disable-analyzer
	--disable-bootstrap
	--disable-cet
	--disable-default-pie
	--disable-default-ssp
	# XXX: This ends up breaking the build on some versions
	#--disable-fixincludes
	--disable-gcov
	--disable-libada
	--disable-libgomp
	--disable-libitm
	--disable-libquadmath
	--disable-libsanitizer
	--disable-libssp
	--disable-libstdcxx-pch
	--disable-libvtv
	--disable-lto
	--disable-multilib
	--disable-nls
	--disable-objc-gc
	--disable-systemtap
	--disable-werror
	--enable-languages="c,c++" #,fortran
	--prefix="${prefix}"

	--enable-checking=release # yes,extra,rtl

	--without-libatomic
	--without-libbacktrace
	--without-isl
	--without-zstd
	--with-system-zlib

	# This only controls support for LTO, not building with it
	#--enable-lto
	#--with-build-config='bootstrap-lto'
	#--with-build-config='bootstrap-O3'

	# XXX: Things we often want to toggle between builds depending on needs.
	# XXX: Put things here to override earlier defaults
	#--enable-libstdcxx
	#
	#--enable-checking=release
	#--disable-checking
	#--disable-stage1-checking
	#
	#--enable-multilib
	#--with-multilib-list="m32,m64"
)

# Try hard to make sure we're actually using the newly-built thing
# TODO: skip on all of these?
if [[ ${build_from_portage} == 1 ]] ; then
	repo_path="$(portageq get_repo_path "${EROOT:-/}" gentoo)"
	gcc_ver=$(<gcc/BASE-VER)
	gcc_ver=${gcc_ver%%.*}

	EXTRA_ECONF="${gcc_config_args[*]}" USE="vanilla -rust -openmp -fortran -pgo -lto -jit" skip ebuild "${repo_path}/sys-devel/gcc/gcc-${gcc_ver}".*.9999.ebuild digest clean merge

	sudo gcc-config "${CHOST}-${gcc_ver}"
	source /etc/profile
	export CC="${CHOST}-gcc-${gcc_ver}"
	export CXX="${CHOST}-g++-${gcc_ver}"
else
	skip "${gitdir}"/configure "${gcc_config_args[@]}"
	skip make "${gcc_make_args[@]}" -Oline V=1
	skip make -Oline install
fi

(
	fatal cd "${gitdir}"
	fatal git clean -fdx
	fatal git reset --hard HEAD
)

#
# Bug-specific testcase goes here
#

# At this point, your GCC is at ${prefix}/bin/gcc, ${prefix}/bin/g++, etc.

# Various examples to adapt as necessary.
if false ; then
	#fatal cd ~/git/gcc/host-x86_64-pc-linux-gnu/gcc

	#rm output.txt
	#./xgcc -B$(pwd) -c -std=c++20 "${TMPDIR}/foo.cxx" &> output.txt
	#if grep -q "${TMPDIR}/foo.cxx:.*error:" output.txt ; then
	#      exit 1
	#fi

	#"${TMPDIR}/bisect/bin/g++" -O2 -Wall -c "${TMPDIR}/foo.cxx"
	#"${TMPDIR}/bisect/bin/gcc" -c -O2 -march=alderlake -g "${TMPDIR}/foo.cxx"
	#"${TMPDIR}/bisect/bin/g++ "-Wfatal-errors '-Werror=stringop-overflow' '-march=nehalem' -O3 -std=c++17 "${TMPDIR}/foo.cxx" -c
	# "${prefix}/bin/g++" -Wfatal-errors -O2 "${TMPDIR}/SkOpAngle.ii"
	ret=$?

	case ${ret} in
		0)
			exit 0
			;;
		*)
			## Something else happened, skip
			#exit 125
			exit 1
			;;
	esac
fi

# Timeout example.
if false ; then
	for x in $(seq 1); do
		# We deliberately exit *0* if it fails because we're bisecting for the bad commit, not good
		timeout 1m "${TMPDIR}/bisect/bin/g++" -Wfatal-errors -O2 "${TMPDIR}/reduced.ii" -c
		timeout_result=$?

		case ${timeout_result} in
			124)
				# Timed out
				exit 1
				;;
			0)
				;;
			*)
				# Something else happened, skip
				exit 125
				;;
			esac
		done
fi

exit 0
