#!/usr/bin/env bash
# TODO:
# bad commits:
# - 6c534857fe7787602eb85baa83a83b6343d9caf3 (xemacs)
# - 24442eaf8850933702eab3e0a89fb781eb2eaacd (ghostscript)
# - 1eafea2300c111f93f6482478095b3b372a67090 (enblend)
# - d45c34870c2f5ab93373be68b536e29f6af74f9a (exact-image)
# - 13c240a2cefccf659cad7f91cfee4bf245b7b90f (rawtherapee)
# - 70e19cb29c796c97f89a870ee991374857014d82 (sane-backends)
# - 1d69eb48210f31783270a1916835d8cde96fafb2 (xastir)
# - 7a5839b17ff31d80f1023cddae7a24f81f27d7d8 (hylafaxplus)
# - 7b8b1ce137eb602bafe40515dbbe63a01e7d1256 (grass)
# - 426db63fb6f16b7702fb6620c73d0ac2c0191e81 (dcmtk)
# - 4050bbe6b94322feaebcbb3c2b7126fc6520b43f (links)
# - 9d8d66eb5921be4194a4c2a5697680fe6071ab56 (lcms)

. "$(pkg-config iwdevtools --variable=atomf)" || { eerror "Could not find iwdevtools' atomf library! Emerge app-portage/iwdevtools?" ; exit 1; }
. /lib/gentoo/functions.sh || { echo "Failed to source functions.sh!" ; exit 1 ; }

# Get a list of the files changed
list=$(git diff --name-only | grep -v "/layout/" | grep -v "/metadata/")

# Parse out the directories to make it easier to see metadata.xml
dirs=()
for file in ${list[@]} ; do
	dirs+=($(dirname "${file}"))
done

# Mangle the format for iteration
dirs=($(echo ${dirs[@]} | tr ' ' '\n' | sort -u))

# Needs a metadata cache for the live check
#pmaint regen .

# Iterate over all of the files changed locally (unstaged)
for dir in ${dirs[@]} ; do
	if [[ ${dir} == *eclass* ]] || [[ ${dir} == *metadata* ]] ; then
		continue
	fi

	dir=${dir/files/}

	cd "${dir}"

	einfo "Iterating over ${dir}"
	eindent

	vers=( $(ls -1 *.ebuild | sort) )

	declare -A revision_map

	for version in "${vers[@]}" ; do
		atomset $(dirname ${dir})/${version%%.ebuild}
		revision_map[${PV}]=0
	done

	# Versions where the content didn't change (think e.g. Emacs
	# where have multiple slots and only changed >= 23, we don't want to
	# revbump 18 needlessly).
	no_change_versions=()

	for x in "${vers[@]}" ; do
		atomset $(dirname ${dir})/${x%%.ebuild}

		if grep -q "PROPERTIES.*live" ../../metadata/md5-cache/${CATEGORY}/${PF} ; then
			continue
		fi

		# If this version didn't change at all, skip it.
		if git diff --exit-code ../../${dir}/${PF}.ebuild &> /dev/null ; then
			no_change_versions+=( "${CATEGORY}/${PF}" )
		fi

		largest_revision=${revision_map[${PV}]}
		if [[ ${PR/r} -gt ${largest_revision} ]] ; then
			revision_map[${PV}]=${PR/r}
		fi
	done

	# Another loop because sort doesn't always get our versioning right.
	# TODO: could probably drop this as I think that's only an issue
	# with PV.
	for x in "${vers[@]}" ; do
		atomset $(dirname ${dir})/${x%%.ebuild}

		if (printf '%s\n' "${no_change_versions[@]}" | grep -xq "${CATEGORY}/${PF}") ; then
			ewarn "Skipping ${CATEGORY}/${P} as nothing changed"
			continue
		fi

		if grep -q "PROPERTIES.*live" ../../metadata/md5-cache/${CATEGORY}/${PF} ; then
			continue
		fi

		largest_revision=${revision_map[${PV}]}
		if [[ ${largest_revision} -eq -1 ]] ; then
			# Already shown, skip.
			continue
		fi

		einfo "${PV} has max revision ${largest_revision}"

		# Don't show again.
		revision_map[${PV}]=-1

		revision=${largest_revision}

		for xrevision in '' ${PR/r} $(seq ${PR/r} $((${largest_revision} - 1))) ; do
			if [[ -n ${xrevision} && ${xrevision} != 0 ]] ; then
				git mv ${P}-r${xrevision}.ebuild ${P}-r$((${revision} + 1)).ebuild
			else
				git mv ${P}.ebuild ${P}-r$((${revision} + 1)).ebuild
			fi

			revision=$((revision + 1))
		done
	done

	eoutdent

	cd ../..
done
